-- Setup roles, warehouse, database, schemas, and stages

CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_NAME);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($WAREHOUSE_NAME)
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 1800
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS IDENTIFIER($DATABASE_NAME);

USE DATABASE IDENTIFIER($DATABASE_NAME);

-- Remove auto-created PUBLIC schema for clarity
DROP SCHEMA IF EXISTS PUBLIC;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ATOMIC;
CREATE SCHEMA IF NOT EXISTS DATA_SCIENCE;

CREATE STAGE IF NOT EXISTS RAW.DATA_STAGE;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE ON DATABASE IDENTIFIER($DATABASE_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON SCHEMA RAW TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON SCHEMA ATOMIC TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON SCHEMA DATA_SCIENCE TO ROLE IDENTIFIER($ROLE_NAME);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA RAW TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ATOMIC TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA DATA_SCIENCE TO ROLE IDENTIFIER($ROLE_NAME);

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA RAW TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA ATOMIC TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DATA_SCIENCE TO ROLE IDENTIFIER($ROLE_NAME);

GRANT SELECT ON ALL VIEWS IN SCHEMA RAW TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON ALL VIEWS IN SCHEMA ATOMIC TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON ALL VIEWS IN SCHEMA DATA_SCIENCE TO ROLE IDENTIFIER($ROLE_NAME);

GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ATOMIC TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DATA_SCIENCE TO ROLE IDENTIFIER($ROLE_NAME);

GRANT READ, WRITE ON STAGE RAW.DATA_STAGE TO ROLE IDENTIFIER($ROLE_NAME);

-- Grant role to current user so deploy can switch to it
GRANT ROLE IDENTIFIER($ROLE_NAME) TO USER IDENTIFIER($MY_USER);
