-- Core tables for UPIP demo

USE DATABASE IDENTIFIER($DATABASE_NAME);

CREATE TABLE IF NOT EXISTS RAW.PLM_EXPORTS (
    LOCAL_ID STRING NOT NULL,
    SOURCE_SYSTEM STRING NOT NULL,
    PART_DESCRIPTION STRING,
    MATERIAL STRING,
    WEIGHT NUMBER(10, 3),
    DIMENSIONS_JSON VARIANT,
    COST NUMBER(12, 2),
    SUPPLIER_ID STRING,
    BUSINESS_UNIT STRING,
    COMPLIANCE_STATUS STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ATOMIC.PART_MASTER (
    GLOBAL_ID STRING NOT NULL,
    LOCAL_ID STRING NOT NULL,
    SOURCE_SYSTEM STRING NOT NULL,
    PART_NAME STRING,
    PART_DESCRIPTION STRING,
    MATERIAL STRING,
    WEIGHT NUMBER(10, 3),
    DIMENSIONS_JSON VARIANT,
    COST NUMBER(12, 2),
    SUPPLIER_ID STRING,
    BUSINESS_UNIT STRING,
    INVENTORY_QUANTITY NUMBER(12, 0),
    INVENTORY_VALUE NUMBER(14, 2),
    COMPLIANCE_STATUS STRING,
    IS_DUPLICATE BOOLEAN DEFAULT FALSE,
    PART_CATEGORY STRING,  -- Valve, Motor, Fastener, Actuator, etc.
    BENCHMARK_COST NUMBER(12, 2),  -- Should-cost reference for variance analysis
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (GLOBAL_ID) RELY
);

CREATE TABLE IF NOT EXISTS ATOMIC.SUPPLIER_MASTER (
    SUPPLIER_ID STRING NOT NULL,
    SUPPLIER_NAME STRING,
    SUPPLIER_REGION STRING,
    RATING NUMBER(3, 1),
    AVG_LEAD_TIME_DAYS NUMBER(6, 0),
    PREFERRED_FLAG BOOLEAN DEFAULT FALSE,
    TOTAL_SPEND NUMBER(14, 2),
    SUPPLIER_TIER STRING DEFAULT 'Approved',  -- Preferred, Approved, Conditional
    CONTRACT_END_DATE DATE,
    QUALITY_CERTIFICATION STRING,  -- ISO 9001, ISO 13485, etc.
    PRIMARY KEY (SUPPLIER_ID) RELY
);

CREATE TABLE IF NOT EXISTS DATA_SCIENCE.PART_SIMILARITY_SCORES (
    SOURCE_GLOBAL_ID STRING NOT NULL,
    TARGET_GLOBAL_ID STRING NOT NULL,
    SIMILARITY_SCORE NUMBER(5, 2),
    MATCH_REASON STRING,
    GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.ENGINEERING_DOCS (
    DOC_ID STRING NOT NULL,
    PART_FAMILY STRING,
    REGULATORY_STANDARD STRING,
    DOC_TEXT STRING,
    SOURCE_URI STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- PROCUREMENT & ANALYTICS TABLES (Multi-Persona Support)
-- ============================================================

-- Simulated PO data for procurement cycle tracking
CREATE TABLE IF NOT EXISTS ATOMIC.PURCHASE_ORDERS (
    PO_ID STRING NOT NULL,
    PART_GLOBAL_ID STRING,
    SUPPLIER_ID STRING,
    QUANTITY NUMBER(12, 0),
    UNIT_PRICE NUMBER(12, 2),
    TOTAL_AMOUNT NUMBER(14, 2),
    PO_STATUS STRING DEFAULT 'draft',  -- draft, approved, received
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    APPROVED_AT TIMESTAMP_NTZ,
    RECEIVED_AT TIMESTAMP_NTZ,
    IS_MAVERICK BOOLEAN DEFAULT FALSE,  -- Purchased outside contract
    PRIMARY KEY (PO_ID) RELY
);

-- Supplier risk scoring for strategic analysis
CREATE TABLE IF NOT EXISTS DATA_SCIENCE.SUPPLIER_RISK_SCORES (
    SUPPLIER_ID STRING NOT NULL,
    FINANCIAL_RISK NUMBER(3, 2),  -- 0.00-1.00
    DELIVERY_RISK NUMBER(3, 2),
    QUALITY_RISK NUMBER(3, 2),
    COMPOSITE_RISK NUMBER(3, 2),
    SUPPLY_CONTINUITY NUMBER(3, 2),  -- Higher = more reliable
    SCORED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUPPLIER_ID) RELY
);

-- Part reuse tracking for R&D engineer metrics
CREATE TABLE IF NOT EXISTS DATA_SCIENCE.PART_REUSE_EVENTS (
    EVENT_ID STRING NOT NULL,
    PART_GLOBAL_ID STRING NOT NULL,
    PROJECT_NAME STRING,
    DESIGN_TIME_SAVED_HOURS NUMBER(6, 1),
    COST_AVOIDED NUMBER(12, 2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_ID) RELY
);

-- Consolidation scenario modeling for VP dashboard
CREATE TABLE IF NOT EXISTS DATA_SCIENCE.CONSOLIDATION_SCENARIOS (
    SCENARIO_ID STRING NOT NULL,
    SCENARIO_NAME STRING,
    SOURCE_SUPPLIERS ARRAY,
    TARGET_SUPPLIER_ID STRING,
    PARTS_AFFECTED NUMBER(8, 0),
    PROJECTED_SAVINGS NUMBER(14, 2),
    IMPLEMENTATION_COST NUMBER(14, 2),
    ROI_PCT NUMBER(5, 2),
    STATUS STRING DEFAULT 'proposed',  -- proposed, approved, in_progress, completed
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SCENARIO_ID) RELY
);
