-- Cortex Search service for engineering documents

USE DATABASE IDENTIFIER($DATABASE_NAME);

CREATE OR REPLACE CORTEX SEARCH SERVICE DATA_SCIENCE.ENGINEERING_DOCS_SEARCH
    ON DOC_TEXT
    ATTRIBUTES (PART_FAMILY, REGULATORY_STANDARD)
    WAREHOUSE = $WAREHOUSE_NAME
    TARGET_LAG = '1 minute'
AS
SELECT
    DOC_ID,
    DOC_TEXT,
    PART_FAMILY,
    REGULATORY_STANDARD,
    SOURCE_URI
FROM RAW.ENGINEERING_DOCS;

-- Grant access to the search service
GRANT USAGE ON CORTEX SEARCH SERVICE DATA_SCIENCE.ENGINEERING_DOCS_SEARCH TO ROLE IDENTIFIER($ROLE_NAME);
